export const tickets = [
  {
    "id": 1,
    "event_id": 1,
    "name": "Show de Rock - Área VIP",
    "event_date": "2024-11-15 20:00:00",
    "created_at": "2024-10-08 01:51:03",
    "updated_at": "2024-10-08 01:51:03",
    "ticket_batches": [
      {
        "id": 1,
        "uuid": "66d5b2cc-e743-4db4-91e9-80b7e4cb47b5",
        "event_session_id": 1,
        "name": "Primeiro Lote",
        "is_current": 0,
        "sort": 1,
        "start_date": "2024-10-01 00:00:00",
        "end_date": "2024-10-15 23:59:59",
        "sold_out": 1,
        "sold_out_at": "2024-10-05 18:00:00",
        "sale_type": "individual",
        "created_at": "2024-10-08 01:51:03",
        "updated_at": "2024-10-08 01:51:03",
        "tickets": [
          {
            "id": 1,
            "event_ticket_lot_id": 1,
            "name": "Ingresso Promoção",
            "ticket_type": "paid",
            "quantity": 6,
            "min_quantity": 1,
            "max_quantity": 4,
            "price": 75.00,
            "is_visible": 1,
            "include_fee": 0,
            "tax": 5.00,
            "code": "PROMO1",
            "sales_quantity": 43,
            "sold_out": 0,
            "sold_at": "2024-10-05 12:00:00",
            "description": "Ingresso promocional para o primeiro lote.",
            "created_at": "2024-10-08 01:51:03",
            "updated_at": "2024-10-08 01:51:03"
          },
          {
            "id": 2,
            "event_ticket_lot_id": 1,
            "name": "Ingresso Gratuito",
            "ticket_type": "free",
            "quantity": 10,
            "min_quantity": 1,
            "max_quantity": 2,
            "price": 0.00,
            "is_visible": 1,
            "include_fee": 0,
            "tax": 0.00,
            "code": "FREE1",
            "sales_quantity": 10,
            "sold_out": 1,
            "sold_at": "2024-10-06 10:00:00",
            "description": "Ingresso gratuito para convidados especiais.",
            "created_at": "2024-10-08 01:51:03",
            "updated_at": "2024-10-08 02:03:25"
          },
          {
            "id": 3,
            "event_ticket_lot_id": 1,
            "name": "Ingresso Open Bar",
            "ticket_type": "paid",
            "quantity": 20,
            "min_quantity": 1,
            "max_quantity": 3,
            "price": 120.00,
            "is_visible": 1,
            "include_fee": 1,
            "tax": 10.00,
            "code": "OPENBAR",
            "sales_quantity": 18,
            "sold_out": 0,
            "sold_at": null,
            "description": "Acesso ao open bar durante o evento.",
            "created_at": "2024-10-08 01:51:03",
            "updated_at": "2024-10-08 01:51:03"
          },
          {
            "id": 4,
            "event_ticket_lot_id": 1,
            "name": "Ingresso Premium",
            "ticket_type": "paid",
            "quantity": 30,
            "min_quantity": 1,
            "max_quantity": 5,
            "price": 150.00,
            "is_visible": 1,
            "include_fee": 1,
            "tax": 15.00,
            "code": "PREMIUM",
            "sales_quantity": 24,
            "sold_out": 0,
            "sold_at": "2024-10-07 18:30:00",
            "description": "Acesso premium com benefícios exclusivos.",
            "created_at": "2024-10-08 01:51:03",
            "updated_at": "2024-10-08 01:51:03"
          }
        ]
      },
      {
        "id": 2,
        "uuid": "30b52646-f0a4-48b4-a1dc-acb33aa26394",
        "event_session_id": 1,
        "name": "Segundo Lote",
        "is_current": 1,
        "sort": 2,
        "start_date": "2024-10-16 00:00:00",
        "end_date": "2024-10-31 23:59:59",
        "sold_out": 0,
        "sold_out_at": null,
        "sale_type": "individual",
        "created_at": "2024-10-08 01:51:03",
        "updated_at": "2024-10-08 01:51:03",
        "tickets": [
          {
            "id": 5,
            "event_ticket_lot_id": 2,
            "name": "Ingresso Mezanino",
            "ticket_type": "paid",
            "quantity": 25,
            "min_quantity": 1,
            "max_quantity": 5,
            "price": 90.00,
            "is_visible": 1,
            "include_fee": 1,
            "tax": 8.00,
            "code": "MEZANINO",
            "sales_quantity": 20,
            "sold_out": 0,
            "sold_at": null,
            "description": "Assento reservado no mezanino.",
            "created_at": "2024-10-08 01:51:03",
            "updated_at": "2024-10-08 01:51:03"
          },
          {
            "id": 6,
            "event_ticket_lot_id": 2,
            "name": "Ingresso Especial",
            "ticket_type": "paid",
            "quantity": 40,
            "min_quantity": 1,
            "max_quantity": 3,
            "price": 110.00,
            "is_visible": 1,
            "include_fee": 0,
            "tax": 12.00,
            "code": "ESPECIAL",
            "sales_quantity": 35,
            "sold_out": 0,
            "sold_at": null,
            "description": "Ingresso especial com área reservada.",
            "created_at": "2024-10-08 01:51:03",
            "updated_at": "2024-10-08 02:03:25"
          },
          {
            "id": 7,
            "event_ticket_lot_id": 2,
            "name": "Ingresso Promoção",
            "ticket_type": "paid",
            "quantity": 50,
            "min_quantity": 1,
            "max_quantity": 4,
            "price": 85.00,
            "is_visible": 1,
            "include_fee": 1,
            "tax": 7.00,
            "code": "PROMO2",
            "sales_quantity": 40,
            "sold_out": 0,
            "sold_at": null,
            "description": "Promoção especial para o segundo lote.",
            "created_at": "2024-10-08 01:51:03",
            "updated_at": "2024-10-08 01:51:03"
          },
          {
            "id": 8,
            "event_ticket_lot_id": 2,
            "name": "Ingresso Premium",
            "ticket_type": "paid",
            "quantity": 20,
            "min_quantity": 1,
            "max_quantity": 3,
            "price": 160.00,
            "is_visible": 1,
            "include_fee": 1,
            "tax": 15.00,
            "code": "PREMIUM2",
            "sales_quantity": 10,
            "sold_out": 0,
            "sold_at": null,
            "description": "Ingresso premium com benefícios adicionais.",
            "created_at": "2024-10-08 01:51:03",
            "updated_at": "2024-10-08 01:51:03"
          }
        ]
      }
    ]
  }
];
